//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Islamic_Dreams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKS_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKS_INFO()
        {
            this.KEY_WORDS = new HashSet<KEY_WORDS>();
        }
    
        public int BOOK_ID { get; set; }
        public string BOOK_URDU { get; set; }
        public string BOOK_ENG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEY_WORDS> KEY_WORDS { get; set; }
    }
}
