//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Islamic_Dreams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCLUTION_LIST
    {
        public int EXC_ID { get; set; }
        public string EXCLUTION_TEXT { get; set; }
        public bool IS_ENGLISH { get; set; }
    }
}
