//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Islamic_Dreams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAM_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMAM_INFO()
        {
            this.DATA_SETS = new HashSet<DATA_SETS>();
        }
    
        public int IMAM_ID { get; set; }
        public string IMAM_ENG { get; set; }
        public string IMAM_URDU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATA_SETS> DATA_SETS { get; set; }
    }
}
