//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Islamic_Dreams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDEX_TABLE
    {
        public int INDEX_ID { get; set; }
        public string INDEX_ENGLISH { get; set; }
        public string INDEX_URDU { get; set; }
        public Nullable<bool> INDEX_STATUS { get; set; }
        public int TOTAL_COUNT { get; set; }
    }
}
