//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Islamic_Dreams.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbConnection : DbContext
    {
        public DbConnection()
            : base("name=DbConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP_USERS> APP_USERS { get; set; }
        public virtual DbSet<BOOKS_INFO> BOOKS_INFO { get; set; }
        public virtual DbSet<DATA_SETS> DATA_SETS { get; set; }
        public virtual DbSet<IMAM_INFO> IMAM_INFO { get; set; }
        public virtual DbSet<KEY_WORDS> KEY_WORDS { get; set; }
        public virtual DbSet<V_DREAMS_DATA> V_DREAMS_DATA { get; set; }
        public virtual DbSet<V_KEYWORDS> V_KEYWORDS { get; set; }
        public virtual DbSet<EXCLUTION_LIST> EXCLUTION_LIST { get; set; }
        public virtual DbSet<INDEX_TABLE> INDEX_TABLE { get; set; }
    }
}
