//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Islamic_Dreams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_KEYWORDS
    {
        public int BOOK_ID { get; set; }
        public string BOOK_URDU { get; set; }
        public string BOOK_ENG { get; set; }
        public int KEY_CODE { get; set; }
        public string KEY_ENGLISH { get; set; }
        public string KEY_URDU { get; set; }
        public int FK_BOOK_REF { get; set; }
    }
}
